# -*- coding: utf-8 -*-
"""DSPL(ICW).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cfIQIJIUk0ZUe84_5hVXNWMKUg_MNmTo
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

file_path = '/content/drive/MyDrive/DSPL ICW/Dataset/Existed/OWID_CB_CO2_INCLUDING_LUC_PER_GDP.csv'
df = pd.read_csv(file_path)

# Display the first few rows of the DataFrame
print(df.head())

df = pd.read_csv(file_path)
print("DataFrame reloaded.")

df = df.rename(columns={"OBS_VALUE": "co2_per_gdp"})
print("Column 'OBS_VALUE' renamed to 'co2_per_gdp'.")

print("DataFrame info before dropping NaNs:")
df.info()

df = df.dropna(subset=['co2_per_gdp'])
print("Rows with missing 'co2_per_gdp' values have been removed.")
print("New DataFrame shape:", df.shape)
display(df.head())

print("Unique Reference Areas (Countries):\n", df['REF_AREA_LABEL'].unique())
print("\nNumber of Unique Reference Areas:", df['REF_AREA_LABEL'].nunique())

print("Unique Indicator Labels:\n", df['INDICATOR_LABEL'].unique())
print("\nNumber of Unique Indicator Labels:", df['INDICATOR_LABEL'].nunique())

print("Time Period Range: Minimum =", df['TIME_PERIOD'].min(), ", Maximum =", df['TIME_PERIOD'].max())

df_cleaned = df[['REF_AREA_LABEL', 'TIME_PERIOD', 'co2_per_gdp']].copy()
print("Selected relevant columns.")

# Filter out 'World' if focusing on individual countries
df_cleaned = df_cleaned[df_cleaned['REF_AREA_LABEL'] != 'World']
print("Filtered out 'World' entry.")

print("New DataFrame head:")
display(df_cleaned.head())
print("New DataFrame info:")
df_cleaned.info()

df_cleaned = df_cleaned.rename(columns={
    'REF_AREA_LABEL': 'country',
    'TIME_PERIOD': 'year'
})
df_cleaned.head()

df_cleaned.info()

import os

save_directory = '/content/drive/MyDrive/DSPL ICW/Dataset/New'
file_name = 'co2_emissions_cleaned.csv'

# Create the directory if it doesn't exist
os.makedirs(save_directory, exist_ok=True)

save_path = os.path.join(save_directory, file_name)
df_cleaned.to_csv(save_path, index=False)

print(f"Cleaned dataset saved to: {save_path}")

"""## Data Visualization

Let's visualize the CO2 emissions per GDP over time for a few countries to identify trends and patterns.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Select a few countries for demonstration
selected_countries = ['United States', 'China', 'India', 'Germany', 'United Kingdom', 'Brazil']

df_selected_countries = df_cleaned[df_cleaned['country'].isin(selected_countries)]

plt.figure(figsize=(14, 8))
sns.lineplot(data=df_selected_countries, x='year', y='co2_per_gdp', hue='country', marker='o', errorbar=None)
plt.title('CO2 Emissions per GDP Over Time for Selected Countries')
plt.xlabel('Year')
plt.ylabel('CO2 per GDP (kg/$2011)')
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend(title='Country')
plt.tight_layout()
plt.show()

"""Next, let's look at the distribution of CO2 per GDP across all countries in a recent year to understand the spread and identify any outliers."""

# Get data for the most recent year available
latest_year = df_cleaned['year'].max()
df_latest_year = df_cleaned[df_cleaned['year'] == latest_year].sort_values(by='co2_per_gdp', ascending=False)

plt.figure(figsize=(12, 7))
sns.histplot(df_latest_year['co2_per_gdp'], kde=True, bins=30)
plt.title(f'Distribution of CO2 Emissions per GDP in {latest_year}')
plt.xlabel('CO2 per GDP (kg/$2011)')
plt.ylabel('Number of Countries')
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""Let's identify and visualize the top and bottom countries in terms of CO2 emissions per GDP for the latest year available. This can highlight countries with very high or very low emissions intensity relative to their GDP."""

# Select top 10 and bottom 10 countries for the latest year
top_10_co2 = df_latest_year.head(10)
bottom_10_co2 = df_latest_year.tail(10).sort_values(by='co2_per_gdp', ascending=True)

# Combine for plotting
combined_df = pd.concat([top_10_co2, bottom_10_co2])

plt.figure(figsize=(14, 8))
sns.barplot(x='co2_per_gdp', y='country', data=combined_df, palette='viridis', legend=False)
plt.title(f'Top 10 and Bottom 10 Countries by CO2 Emissions per GDP in {latest_year}')
plt.xlabel('CO2 per GDP (kg/$2011)')
plt.ylabel('Country')
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""Let's examine how the distribution of CO2 emissions per GDP has changed over different periods. A box plot for selected years can reveal shifts in central tendency and spread."""

# Select a few representative years to show the evolution of the distribution
representative_years = [1900, 1950, 1980, 2000, latest_year]
df_years_distribution = df_cleaned[df_cleaned['year'].isin(representative_years)]

plt.figure(figsize=(14, 8))
sns.boxplot(x='year', y='co2_per_gdp', data=df_years_distribution, palette='coolwarm')
plt.title('Distribution of CO2 Emissions per GDP Across Selected Years')
plt.xlabel('Year')
plt.ylabel('CO2 per GDP (kg/$2011)')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()